name: Deploy static content to GitHub Pages

on:
  push:
    branches:
      - main  # Set the branch you want to use (replace with the branch you're using)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GitHub Pages
      uses: actions/setup-pages@v2

    - name: Build the site
      run: echo "<!DOCTYPE html><html><body><h1>My GitHub Pages Site</h1></body></html>" > index.html

    - name: Deploy to GitHub Pages
      uses: actions/upload-pages-artifact@v2
      with:
        path: './index.html'

    - name: Deploy GitHub Pages
      uses: actions/deploy-pages@v1
